# Base Information
group_name: "OpenStudioLandscapes_Flamenco_Worker"
key_prefixes:
  - "OpenStudioLandscapes_Flamenco_Worker"

#compose_scope: "worker"

#enabled: true

#flamenco_worker_NUM_SERVICES: 1
