# Base Information
group_name: "OpenStudioLandscapes_Flamenco_Worker"
key_prefixes:
  - "OpenStudioLandscapes_Flamenco_Worker"

#compose_scope: "worker"

# Not enabled by default because this Feature
# has some basic requirements, such as
# the installers
#enabled: false

#deadline_10_2_worker_NUM_SERVICES: 1
